import Vue from "vue";
import {
  Container,
  Checkbox,
  CheckboxGroup,
  DatePicker,
  Main,
  TableColumn,
  Table,
  Header,
  Col,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Dialog,
  Aside,
  Menu,
  Submenu,
  MenuItemGroup,
  MenuItem,
  Row,
  Tabs,
  TabPane,
  Select,
  Option,
  Pagination,
  Avatar,
  Image,
  Form,
  FormItem,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  Button
} from "element-ui";
import lang from "element-ui/lib/locale/lang/en";
import locale from "element-ui/lib/locale";

locale.use(lang);
Vue.use(Container);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Col);
Vue.use(Main);
Vue.use(TableColumn);
Vue.use(Table);
Vue.use(Header);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(Aside);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItemGroup);
Vue.use(MenuItem);
Vue.use(DropdownItem);
Vue.use(TabPane);
Vue.use(Tabs);
Vue.use(Select);
Vue.use(Option);
Vue.use(Avatar);
Vue.use(Image);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Button);
Vue.use(Dialog);
Vue.use(Row);
Vue.use(Pagination);
Vue.use(DatePicker);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(InputNumber);
